- name: Check latest workflow run status
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get latest workflow run
      uri:
        url: "https://api.github.com/repos/{{ lookup('env','GITHUB_OWNER') }}/{{ lookup('env','GITHUB_REPO_NAME') }}/actions/runs"
        method: GET
        headers:
          Authorization: "token {{ lookup('env','GITHUB_TOKEN') }}"
          Accept: "application/vnd.github.v3+json"
      register: result

    - debug:
        var: result.json.workflow_runs[0] 