- name: Download logs for latest workflow run
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get latest workflow run
      uri:
        url: "https://api.github.com/repos/{{ lookup('env','GITHUB_OWNER') }}/{{ lookup('env','GITHUB_REPO_NAME') }}/actions/runs"
        method: GET
        headers:
          Authorization: "token {{ lookup('env','GITHUB_TOKEN') }}"
          Accept: "application/vnd.github.v3+json"
      register: runs

    - set_fact:
        run_id: "{{ runs.json.workflow_runs[0].id }}"

    - name: Download logs
      uri:
        url: "https://api.github.com/repos/{{ lookup('env','GITHUB_OWNER') }}/{{ lookup('env','GITHUB_REPO_NAME') }}/actions/runs/{{ run_id }}/logs"
        method: GET
        headers:
          Authorization: "token {{ lookup('env','GITHUB_TOKEN') }}"
          Accept: "application/vnd.github.v3+json"
        return_content: yes
      register: logs

    - copy:
        content: "{{ logs.content }}"
        dest: "./latest_workflow_logs.zip" 