- name: Trigger GitHub Actions workflow
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Trigger workflow_dispatch event
      uri:
        url: "https://api.github.com/repos/{{ lookup('env','GITHUB_OWNER') }}/{{ lookup('env','GITHUB_REPO_NAME') }}/actions/workflows/main.yml/dispatches"
        method: POST
        headers:
          Authorization: "token {{ lookup('env','GITHUB_TOKEN') }}"
          Accept: "application/vnd.github.v3+json"
        body_format: json
        body:
          ref: "main"
      register: result

    - debug:
        var: result 